image: ruby:2.5.7
services:
  - postgres:9.5
  - docker:dind

variables:
  REGISTRY_URL: registry.gitlab.com/fiuba-memo2/ejemplos
  APP_NAME: webapi-template
  HEROKU_APP: webapi-example
  POSTGRES_DB: webtemplate_test
  POSTGRES_USER: webtemplate
  POSTGRES_PASSWORD: webtemplate
  TEST_DB_URL: postgres://webtemplate:webtemplate@postgres/webtemplate_test
  DB_HOST: postgres
  DEV_HOST: webapi-example.herokuapp.com

stages:
  - build
  - package
  - deploy

build_job:
  stage: build
  script:
    - apt-get update -qq && apt-get install -y -qq postgresql postgresql-contrib libpq-dev cmake # todo check si es necesario
    - gem install bundler --no-document
    - bundle install --without staging production
    - RACK_ENV=test bundle exec rake
    - bundle exec rake version > VERSION.txt
  artifacts:
    paths:
      - VERSION.txt

package_job:
  stage: package
  image: docker:stable
  before_script:
    - echo -n $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
  script:
    - VERSION=$(cat VERSION.txt)
    - echo $VERSION
    - docker build -f Dockerfile.prod --build-arg GIT_COMMIT=$CI_COMMIT_SHORT_SHA -t $REGISTRY_URL/$APP_NAME:$VERSION .
    - docker tag $REGISTRY_URL/$APP_NAME:$VERSION $REGISTRY_URL/$APP_NAME:latest
    - docker push $REGISTRY_URL/$APP_NAME:$VERSION
    - docker push $REGISTRY_URL/$APP_NAME:latest

deploy_dev_job:
  stage: deploy
  image: docker:stable
  before_script:
    - apk add curl
    - echo -n $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
    - docker login -u _ -p $HEROKU_TOKEN registry.heroku.com
  script:
    - VERSION=$(cat VERSION.txt)
    - docker pull $REGISTRY_URL/$APP_NAME:$VERSION
    - docker tag $REGISTRY_URL/$APP_NAME:$VERSION registry.heroku.com/$HEROKU_APP/web
    - docker push registry.heroku.com/$HEROKU_APP/web
    - export IMAGE_ID=`docker inspect registry.heroku.com/$HEROKU_APP/web --format={{.Id}}`
    - echo $IMAGE_ID
    - ./scripts/deploy_app.sh
    - ./scripts/smoke_test.sh $DEV_HOST $VERSION
  only:
    - tags
