version: '3'
services:
  postgres:
    image: postgres:12-alpine
    ports:
      - 5435:5432
    volumes:
      - data:/var/lib/postgresql/data
      - ./scripts/create_dev_and_test_dbs.sql:/docker-entrypoint-initdb.d/create_dev_and_test_dbs.sql
    environment:
      - POSTGRES_PASSWORD=webtemplate

  server:
    build: .
    volumes:
      - ./:/src
    ports:
      - "3000:3000"
    environment:
      - RACK_ENV=development
      - DATABASE_URL=postgres://webtemplate:webtemplate@postgres/webtemplate_development
      - PORT=3000

volumes:
  data: