---
openapi: 3.0.3
info:
  title: moscu-api
  version: 0.12.2
paths:
  "/reset":
    post:
      summary: POST /reset
      responses:
        '200':
          description: POST /reset
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              example:
                message: reset ok
  "/usuarios":
    post:
      summary: POST /usuarios
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nombre:
                  type: string
                id:
                  type: integer
                email:
                  type: string
            example:
              nombre: juan
              id: 123
              email: juan@test.com
      responses:
        '201':
          description: registro exitoso
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  nombre:
                    type: string
                  email:
                    type: string
              example:
                nombre: juan
                id: 123
                email: juan@test.com
        '400':
          description: Error en la API
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              example:
                error: "Error: Hubo un error en la API"
  "/usuarios/{id_usuario}/ofertas":
    get:
      summary: GET /usuarios/{id_usuario}/ofertas
      responses:
        '200':
          description: Consulta de ofertas exitosa
          content:
            application/json:
              schema:
                type: array
                items: 
                  type: object
                  properties:
                    id_oferta:
                      type: integer
                    patente:
                      type: string
                    id_ofertante:
                      type: integer
                    precio:
                      type: integer
                    estado:
                      type: string
                example:
                  - id_oferta: 23
                    patente: ABC123
                    id_ofertante: 123
                    precio: 8000
                    estado: Pendiente
                  - id_oferta: 24
                    patente: ABC123
                    id_ofertante: 124
                    precio: 9000
                    estado: Aceptado
        '400':
          description: Error en la API
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              example:
                error: "Error: Hubo un error en la API"
  "/ofertas/{id_oferta}/rechazar":
    post:
      summary: POST /ofertas/{id_oferta}/rechazar
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id_prop:
                  type: integer
            example:
              id_prop: 123
      responses:
        '200':
          description: Rechazo exitoso
          content:
            application/json:
              schema:
                type: object
                properties:
                  id_oferta:
                    type: integer
                  patente:
                    type: string
                  id_ofertante:
                    type: integer
                  precio:
                    type: integer
                  estado:
                    type: string
              example:
                id_oferta: 23
                patente: ABC123
                id_ofertante: 123
                precio: 8000
                estado: Rechazado
        '400':
          description: Error en la API
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              example:
                error: "Error: Hubo un error en la API"
  "/ofertas/{id_oferta}/aceptar":
    post:
      summary: POST /ofertas/{id_oferta}/aceptar
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id_prop:
                  type: integer
            example:
              id_prop: 123
      responses:
        '200':
          description: Aceptacion exitosa
          content:
            application/json:
              schema:
                type: object
                properties:
                  id_oferta:
                    type: integer
                  patente:
                    type: string
                  id_ofertante:
                    type: integer
                  precio:
                    type: integer
                  estado:
                    type: string
              example:
                id_oferta: 23
                patente: ABC123
                id_ofertante: 123
                precio: 8000
                estado: Aceptado
        '400':
          description: Error en la API
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              example:
                error: "Error: Hubo un error en la API"
  "/autos":
    post:
      summary: POST /autos
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                patente:
                  type: string
                modelo:
                  type: string
                kilometros:
                  type: integer
                anio:
                  type: integer
                id_prop:
                  type: integer
            example:
              patente: "ABC123"
              modelo: "Fiat Uno"
              kilometros: 10000
              anio: 1995
              id_prop: 1
      responses:
        '201':
          description: registro exitoso
          content:
            application/json:
              schema:
                type: object
                properties:
                  patente:
                    type: string
                  modelo:
                    type: string
                  kilometros:
                    type: integer
                  anio:
                    type: integer
                  id_prop:
                    type: integer
                  precio:
                    type: integer
                  estado:
                    type: string
              example:
                patente: "ABC123"
                modelo: "Fiat Uno"
                kilometros: 10000
                anio: 1995
                id_prop: 1
                precio: 0
                estado: 'En revision'
        '400':
          description: Error en la API
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              example:
                error: "Error: Hubo un error en la API"
  "/autos/{patente}/cotizar":
    patch:
      summary: PATCH /autos/{patente}/cotizar
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                precio:
                  type: integer
            example:
              precio: 50000
      responses:
        '200':
          description: Cotizacion exitosa
          content:
            application/json:
              schema:
                type: object
                properties:
                  patente:
                    type: string
                  modelo:
                    type: string
                  kilometros:
                    type: integer
                  anio:
                    type: integer
                  id_prop:
                    type: integer
                  precio:
                    type: integer
                  estado:
                    type: string
              example:
                patente: "ABC123"
                modelo: "Fiat Uno"
                kilometros: 10000
                anio: 1995
                id_prop: 1
                precio: 50000
                estado: 'Cotizado'
        '400':
          description: Error en la API
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              example:
                error: "Error: Hubo un error en la API"
  "/autos/{patente}/vender_a_fiubak":
    post:
      summary: POST /autos/{patente}/vender_a_fiubak
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id_prop:
                  type: integer
            example:
              id_prop: 1
      responses:
        '200':
          description: Venta a Fiubak exitosa
          content:
            application/json:
              schema:
                type: object
                properties:
                  patente:
                    type: string
                  modelo:
                    type: string
                  kilometros:
                    type: integer
                  anio:
                    type: integer
                  id_prop:
                    type: integer
                  precio:
                    type: integer
                  estado:
                    type: string
              example:
                patente: "ABC123"
                modelo: "Fiat Uno"
                kilometros: 10000
                anio: 1995
                id_prop: 1
                precio: 50000
                estado: 'Esperando entrega'
        '400':
          description: Error en la API
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              example:
                error: "Error: Hubo un error en la API"
  "/autos/{patente}/entregar_llaves":
    post:
      summary: POST /autos/{patente}/entregar_llaves
      responses:
        '200':
          description: Entrega de llaves exitosa
          content:
            application/json:
              schema:
                type: object
                properties:
                  patente:
                    type: string
                  modelo:
                    type: string
                  kilometros:
                    type: integer
                  anio:
                    type: integer
                  id_prop:
                    type: integer
                  precio:
                    type: integer
                  estado:
                    type: string
              example:
                patente: "ABC123"
                modelo: "Fiat Uno"
                kilometros: 10000
                anio: 1995
                id_prop: 1
                precio: 50000
                estado: 'Publicado'
        '400':
          description: Error en la API
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              example:
                error: "Error: Hubo un error en la API"
  "./autos":
    # TODO: no me permite usar /autos por el POST
    # TODO: como se muestra una lista de OpenAPI?
    get:
      summary: GET /autos
      responses:
        '200':
          description: Listado de autos exitoso
          content:
            application/json:
              schema:
                type: object
                properties:
                  autos:
                    type: object
                    properties:
                      patente:
                        type: string
                      modelo:
                        type: string
                      kilometros:
                        type: integer
                      anio:
                        type: integer
                      id_prop:
                        type: integer
                      precio:
                        type: integer
                      estado:
                        type: string
              example:
                autos:
                  patente: "ABC123"
                  modelo: "Fiat Uno"
                  kilometros: 10000
                  anio: 1995
                  id_prop: 1
                  precio: 50000
                  estado: 'Publicado'
        '400':
          description: Error en la API
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              example:
                error: "Error: Hubo un error en la API"
  "/autos/{patente}/publicar_p2p":
    post:
      summary: POST /autos/{patente}/publicar_p2p
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id_prop:
                  type: integer
                precio:
                  type: integer
            example:
              id_prop: 1
              precio: 80000
      responses:
        '200':
          description: Publicacion p2p exitosa
          content:
            application/json:
              schema:
                type: object
                properties:
                  patente:
                    type: string
                  modelo:
                    type: string
                  kilometros:
                    type: integer
                  anio:
                    type: integer
                  id_prop:
                    type: integer
                  precio:
                    type: integer
                  estado:
                    type: string
              example:
                patente: "ABC123"
                modelo: "Fiat Uno"
                kilometros: 10000
                anio: 1995
                id_prop: 1
                precio: 80000
                estado: 'Publicado'
        '400':
          description: Error en la API
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              example:
                error: "Error: Hubo un error en la API"
  "/autos/{patente}/comprar":
    post:
      summary: POST /autos/{patente}/comprar
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id_comprador:
                  type: integer
                precio:
                  type: integer
            example:
              id_comprador: 24
      responses:
        '200':
          description: Compra a Fiubak exitosa
          content:
            application/json:
              schema:
                type: object
                properties:
                  patente:
                    type: string
                  modelo:
                    type: string
                  kilometros:
                    type: integer
                  anio:
                    type: integer
                  id_prop:
                    type: integer
                  precio:
                    type: integer
                  estado:
                    type: string
              example:
                patente: "ABC123"
                modelo: "Fiat Uno"
                kilometros: 10000
                anio: 1995
                id_prop: 1
                precio: 50000
                estado: 'Vendido'
        '400':
          description: Error en la API
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              example:
                error: "Error: Hubo un error en la API"
