---
openapi: 3.0.3
info:
  title: moscu-api
  version: 0.12.2
paths:
  "/reset":
    post:
      summary: POST /reset
      responses:
        '200':
          description: POST /reset
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              example:
                message: reset ok
  "/usuarios":
    post:
      summary: POST /usuarios
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nombre:
                  type: string
                id:
                  type: integer
                email:
                  type: string
            example:
              nombre: juan
              id: 123
              email: juan@test.com
      responses:
        '201':
          description: POST /usuarios
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  nombre:
                    type: string
                  email:
                    type: string
              example:
                nombre: juan
                id: 123
                email: juan@test.com
        '400':
          description: POST /usuarios
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              example:
                error: "Error: Hubo un error en la API"